#!/usr/bin/env bash
# Per-mood ANIMATION FRAMES (v0.8.0 "he moves"). Same locked seed 501 + same
# style/room, varied POSE. Text-to-image can't tween cleanly, so we never tween:
# we CUT between frames (comic/limited-animation style), which hides the drift
# and reads as real motion.
#   <mood>.jpg   — base (already generated by gen_art.sh)
#   <mood>_b.jpg — an alternate idle pose; slow cut base<->b = he breathes/shifts
#   <mood>_hit.jpg — an extreme reaction pose; cut here the instant a hit lands
set -euo pipefail
cd "$(dirname "$0")/.."
STYLE="glossy cel-shaded manhwa noir, crisp clean digital rendering, sharp detailed eyes, dramatic crimson overhead light single hanging bulb, film-noir crime backroom, high production"
BASE="a dangerous debt collector in a dark suit seated at the FAR side of a long table facing the viewer, full wide shot showing the whole table and the dim room around him, POV from across the table"
D=public/assets/art/collector

gen() { # gen <out> <pose>
  local enc
  enc=$(python3 -c "import urllib.parse,sys;print(urllib.parse.quote(sys.argv[1]))" "$BASE, $2, $STYLE")
  if curl -fsSL -m 180 -o "$1" "https://image.pollinations.ai/prompt/${enc}?width=1080&height=1600&nologo=true&seed=501&model=flux"; then
    file "$1" | grep -q "image data" && echo "OK $1" || echo "FAIL $1"
  else
    echo "FAIL(curl) $1"
  fi
  sleep 6
}

# guarded — composed, giving nothing
gen $D/guarded_b.jpg   "still and watchful, shifting his weight back, head tilted slightly, guarded"
gen $D/guarded_hit.jpg "caught off guard for an instant, eyes widening slightly, hand frozen mid-air"

# rattled — uneasy
gen $D/rattled_b.jpg   "uneasy, tugging at his collar, glancing away, rattled"
gen $D/rattled_hit.jpg "flinching back hard, jaw clenched, hand jerking to his watch"

# angry — swinging
gen $D/angry_b.jpg     "furious, jabbing a finger across the table, shouting"
gen $D/angry_hit.jpg   "slamming both fists on the table, roaring, half standing"

# cornered — trapped
gen $D/cornered_b.jpg  "sweating, loosening his tie, eyes darting to the door, cornered"
gen $D/cornered_hit.jpg "recoiling, both hands up defensively, panic breaking through"

# folding — done
gen $D/folding_b.jpg   "defeated, head in his hands, elbows on the table"
gen $D/folding_hit.jpg "collapsing back into the chair, hollow, staring at nothing"

echo "=== frames done ==="
ls -la $D
